---
- name: Add Docker GPG key
  shell: |
      curl -fsSL {{ docker_gpg_url }} | sudo tee /etc/apt/trusted.gpg.d/docker.asc
  args:
    creates: /etc/apt/trusted.gpg.d/docker.asc

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] {{ docker_repo }} {{ ansible_distribution_release | lower }} stable"
    state: present
    filename: docker

- name: Update repository
  apt:
    update_cache: yes

- name: Install docker
  apt:
    name: "{{ docker_install_packages}}"
    state: present

- name: Start and enable docker service
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: "{{ docker_group }}"
    append: yes

- name:  Check Docker version
  command: docker --version
  register: docker_version

- name: Show Docker version
  debug:
    msg: "Docker version {{ docker_version.stdout }}"
