version: '3.8'

services:
  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    restart: always
    volumes:
      # Montre les volumes nécessaires pour exporter les métriques du système hôte
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    deploy:
      replicas: 1
      placement:
        # Run on worker node
        constraints:
          - node.role == manager

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

    deploy:
      replicas: 1
      placement:
        # Run on worker node
        constraints:
          - node.role == manager

volumes:
  prometheus_data:
    driver: local
  grafana-storage: {}
