---
- name: Install UFW Firewall
  ansible.builtin.apt:
    name: ufw
    state: present
  
- name: UFW resets existing rules
  community.general.ufw:
    state: reset
  
- name: UFW firewall allow SSH
  community.general.ufw:
    rule: allow
    port: "{{ sshd_ssh_port }}"
  
- name: UFW firewall allow DNS
  community.general.ufw:
    rule: allow
    port: "{{ ufw_port_dns}}"

- name: UFW firewall allow HTTP
  community.general.ufw:
    rule: allow
    port: "{{ ufw_port_http }}"

- name: UFW firewall allow HTTPS
  community.general.ufw:
    rule: allow
    port: "{{ ufw_port_https }}"

- name: UFW firewall allow docker-swarm
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
  loop: "{{ ufw_port_dockerswarm }}"
 
- name: Configure default incoming policy
  community.general.ufw:
    policy: reject
    direction: incoming
  
- name: Configure default outgoing policy
  community.general.ufw:
    policy: allow
    direction: outgoing
  
- name: Enable UFW
  community.general.ufw:
    state: enabled
  notify: "Reload UFW"
  