version: '3.7'

services:
  traefik:
    image: traefik:latest
    command:
      - "--api.insecure=true"
      - "--providers.swarm=true"
      - "--log.level=DEBUG"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=sylvainrougie@orange.fr"
      - "--certificatesresolvers.myresolver.acme.storage=/acme.json"
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik-certificates:/acme.json
    deploy:
      placement:
        constraints:
          - node.role == manager

  web-hippo:
    image: sipixer/hippo_front:latest
    environment:
      - API_PORT=3000
      - API_ADDRESS=localhost
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.web-hippo.rule=Host(`hippo.mangoustes.ynov`)
        - traefik.http.services.web-hippo.loadbalancer.server.port=80
        - traefik.http.routers.web-hippo.entrypoints=web,websecure
        - traefik.http.routers.web-hippo.tls=true
        - traefik.http.routers.web-hippo.tls.certresolver=myresolver

  back-hippo:
    image: sipixer/hippo_back:latest
    environment:
      - PG_USER=myuser
      - PG_PASS=mypassword
      - PG_DB=mydatabase
      - PG_HOST=postgresql-primary
      - API_PORT=3000

    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.back-hippo.rule=Host(`api.hippo.mangoustes.ynov`)
        - traefik.http.services.back-hippo.loadbalancer.server.port=3000
        - traefik.http.routers.back-hippo.entrypoints=web,websecure
        - traefik.http.routers.back-hippo.tls=true
        - traefik.http.routers.back-hippo.tls.certresolver=myresolver

  postgresql-primary:
    image: bitnami/postgresql-repmgr:latest
    environment:
      # Basic Postgres settings
      - POSTGRESQL_POSTGRES_PASSWORD=mypassword
      - POSTGRESQL_USERNAME=myuser
      - POSTGRESQL_PASSWORD=mypassword
      - POSTGRESQL_DATABASE=mydatabase

      # Repmgr primary settings
      - REPMGR_PRIMARY_ROLE=true
      - REPMGR_NODE_NAME=postgresql-primary-0
      - REPMGR_NODE_ID=1
      - REPMGR_NODE_NETWORK_NAME=postgresql-primary
      - REPMGR_PARTNER_NODES=postgresql-primary,postgresql-replica
      - REPMGR_PORT_NUMBER=5432
      - REPMGR_PASSWORD=cool
      - REPMGR_PRIMARY_HOST=postgresql-primary

    volumes:
      - postgres_primary_data:/bitnami/postgresql
    deploy:
      replicas: 1
      placement:
        # Run on the manager host
        constraints:
          - node.role == manager
    ports:
      - "5432:5432" # Expose the port if needed

  postgresql-replica:
    image: bitnami/postgresql-repmgr:latest
    environment:
      # Basic Postgres settings
      - POSTGRESQL_POSTGRES_PASSWORD=mypassword
      - POSTGRESQL_USERNAME=myuser
      - POSTGRESQL_PASSWORD=mypassword
      - POSTGRESQL_DATABASE=mydatabase

      # Repmgr replica settings
      - REPMGR_PRIMARY_ROLE=false
      - REPMGR_NODE_NAME=postgresql-replica-0
      - REPMGR_NODE_ID=2
      - REPMGR_NODE_NETWORK_NAME=postgresql-replica
      - REPMGR_PARTNER_NODES=postgresql-primary,postgresql-replica
      - REPMGR_PORT_NUMBER=5432
      - REPMGR_PASSWORD=cool
      - REPMGR_PRIMARY_HOST=postgresql-primary

    volumes:
      - postgres_replica_data:/bitnami/postgresql
    deploy:
      replicas: 1
      placement:
        # Run on worker node
        constraints:
          - node.role == worker

networks:
  default:
    driver: overlay

volumes:
  traefik-certificates:
  postgres_primary_data:
    driver: local
  postgres_replica_data:
    driver: local
